### ISSUE TITLE
Automate the ctags-snap testing procedure

### ISSUE THREAD

**Issue by tartley** [universal-ctags/ctags-snap#13]
The README brilliantly describes the procedure to build the snap, install it, and test the installed executable. This process, or an equivalent to it, should be automated so it can be run regularly by contributors, without fear of typos, and automatically run on releases, by CI, etc.

**Comment by masatake** [comment]
This is a really good idea.
@KazuakiM took this approach in his https://github.com/universal-ctags/homebrew-universal-ctags.

**Comment by masatake** [comment]
I don't know well about Teams and Collaborators management on github.
If your "right" is not enough for running automatic testing on CI environment like Travis, let me know.
I will study the management.

**Comment by tartley** [comment]
test is automated in a Makefile. I'll create a separate issue to use this Makefile in a CI like travis...
