### ISSUE TITLE
Create CI for the built snap

### ISSUE THREAD

**Issue by tartley** [universal-ctags/ctags-snap#18]
When manually triggered
Then Travis CI runs a build and test of this repo's current state
and fails if a valid tags file is not generated

**Comment by masatake** [comment]
ctags source tree itself has test sweets. The major one is units and tmain.
Run like this:
```
make units tmain CTAGS_TEST=/home/yamato/var/ctags-github/ctags
```
units tests each parser.
tmain test the common part which we call 'main'.

http://docs.ctags.io/en/latest/testing.html

**Comment by tartley** [comment]
@masatake Thanks, that's great to know about.

My vision is that the ctags tests you described will already have been run on commits merged to master in universal-ctags. So I don't need to run them again. I can just run a small sanity-check test that confirms that ctags-snap:
* ctags-snap can build a snap from the latest ctags source
* we can install the resulting snap
* we can run the installed executable and make a very trivial confirmation that it produces sane output. (eg check the tag for my 'sample' directory.)

This is all done, I don't plan to do any more. Let me know if that sounds crazy.

**Comment by tartley** [comment]
We now get Travis builds on each push to ctags-snap:
https://travis-ci.org/universal-ctags/ctags-snap/builds/587528581

and can still run the same test locally, using 'make' as documented in our README.
