### ISSUE TITLE
[help] install without network access?

### ISSUE THREAD

**Issue by xaljer** [universal-ctags/ctags-snap#23]
I want to install ctags-snap on a linux server without internet access. Does snap support install/run using a single file like appimage? if so, provide files in the release page?

**Comment by tartley** [comment]
Sounds do-able. I'll try and do it tomorrow. (and will also look into whether 'snap' itself can give you access to the files)

**Comment by tartley** [comment]
Finally done it! https://github.com/universal-ctags/ctags-snap/releases/tag/rev14

I'm not currently planning on doing this for every minor release, just for major new releases / fixes. Shout if that sounds bad.

**Comment by tartley** [comment]
Finally done it! [revision 14](https://github.com/universal-ctags/ctags-snap/releases/tag/rev14)

I'm not currently planning on doing this for every minor release, just for major new releases / fixes. Shout if that sounds bad.

**Comment by xaljer** [comment]
That's cool, i will try it. Thank you.
