### ISSUE TITLE
Tag output seems incorrect when using multi-line regex

### ISSUE THREAD

**Issue by stevenengler** [universal-ctags/ctags-snap#24]
Using a multiline regex seems to give strange results. The example below shows the tag output pointing to an empty line, but in real code it will point to other non-associated functions elsewhere in the file, not just empty lines.

The name of the parser: C (with custom regex)

The command line you used to run ctags:
```
$ ctags --options=NONE --mline-regex-c='/MOCK_IMPL\([^,]+,\W*([a-zA-Z0-9_]+)\W*,/\1/f/' test.c
```

The content of input file (empty lines indicated since GitHub will remove them):
```
<empty line>
MOCK_IMPL(int,
test_function,(int x, int y)
<empty line>
```

The tags output you are not satisfied with:
```
test_function   test.c  /^$/;"  f
```

The tags output you expect:

Something other than an empty line, such as:
```
test_function   test.c  /^test_function,(int x, int y)$/;"  f
...
```

The version of ctags:
```
$ ctags --version
Universal Ctags 0.0.0(9fcdb065), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Nov  6 2019, 22:41:07
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +packcc
```

How do you get ctags binary:

From the snap package.

**Comment by masatake** [comment]
@tartley, thank you for responding. I transferred  the issue to ctags-snap.

**Comment by tartley** [comment]
I have a local build of a snap with this fix in place, and it fixes both of the above problems.

I've pushed it to the store, but unfortunately I recently made some unrelated changes to the snap to sidestep security restrictions, so we're on a temporary period of manual review of new uploads. I'll post here when the fixed version is installable.

**Comment by masatake** [comment]
How do you think adding "Suggested by @stevenengler" to the commit log?

**Comment by stevenengler** [comment]
Thanks for fixing this, I'll keep an eye out for the updated snap.

And don't worry about crediting me or anything, I'm just happy that I got help so quickly here :)

**Comment by tartley** [comment]
FWIW, the release containing this fix, and other releases since, were promoted to 'stable' a while ago. I'm closing this issue. Thanks everyone.
