### ISSUE TITLE
Understand ctags releases and versioning

### ISSUE THREAD

**Issue by tartley** [universal-ctags/ctags-snap#9]
The new snap maintainer (@tartley) does not yet understand what version numbers to use on snap releases. Does the ctags repo have tags or releases, or is some other mechanism used to decide when to package a release? What do the other packaging formats do?

**Comment by masatake** [comment]
I have no plan to make a release or to put tag on our git repo in various reason.
I don't know how the original snap author did.
However, you may be interested in how @k-takata does in https://github.com/universal-ctags/ctags-win32.

**Comment by tartley** [comment]
Good to know. Thanks.
